### PR TITLE
Add a failing test for #51

### PR DESCRIPTION
**Pull request by stephenmathieson**

### CODE REVIEW

**Comment by stephenmathieson** [comment]
wtf this passed the build?  can you verify @jwerle?

**Comment by jwerle** [comment]
Ah I see what is happening..

See https://github.com/sphia/sphia/blob/master/Makefile#L29

The `foreach` macro in `make` doesn't yield to non 0 exit statuses..

**Comment by jwerle** [comment]
We should consider doing it with bash

**Comment by stephenmathieson** [comment]
Good plan.

BTW, I'm pretty sure our get/set bug is result of using `strlen`.  See [this](https://github.com/pmwkaa/sophia/blob/master/test/issues.c#L26) and note the usage of `sizeof`.  It looks like we're specifying `ksize` wrong everywhere.  I'm working on a refactor branch, but `sphia_get` needs a full rewrite :(

**Comment by jwerle** [comment]
Yeah I saw that. We can split up the work. Which do you prefer to tackle, get or set?

**Comment by stephenmathieson** [comment]
I'll ping you

**Pull request merged**
