### PR TITLE
Add travis rule

### PR DESCRIPTION
**Pull request by larzconwell**
Any idea what os travis does testing on? I assume Linux, but if not we should figure out and test on it before merging. I'm not sure how compilers on other systems handle the LIBRARY_PATH environment variable.

### CODE REVIEW

**Comment by stephenmathieson** [comment]
Great awesome man!  I'll review when I get home. 

I believe it's Ubuntu ~10.4, though I'm not sure.

**Comment by jwerle** [comment]
Woot !! LGTM

**Comment by jwerle** [comment]
I guess the only way we can test this is running a job on travis ci..

**Comment by larzconwell** [comment]
Yep haha

**Comment by stephenmathieson** [comment]
Awesome man!!

**Comment by jwerle** [comment]
Win!!

**Pull request merged**
