### PR TITLE
Install deps with clib-install(1) and add deps to package.json

### PR DESCRIPTION
**Pull request by stephenmathieson**

### CODE REVIEW

**Comment by jwerle** [comment]
The commander dep overrides how we display usage. How do you guys feel about that?

**Comment by stephenmathieson** [comment]
I don't think editing our deps' sources is a good idea.  If we can't live with how commander displays usage, can we fix it?

EDIT: or just drop the dep entirely?  It's already caused `-v` issues...

**Comment by jwerle** [comment]
Hmm true. I think for now we can just utilize commander and display it how commander does. We will have a clearly defined cli once libsphia is done

**Comment by jwerle** [comment]
Cool to merge ? @stephenmathieson

**Comment by stephenmathieson** [comment]
I'm always cool with you merging my PRs haha

**Comment by jwerle** [comment]
sweeeeet

**Pull request merged**
