### PR TITLE
refactoring

### PR DESCRIPTION
**Pull request by deepak1556**
Started replacing methods implmented by libsphia, hope i am doing it right? not sure about the travis setup for test. 
/help @jwerle @stephenmathieson @larzconwell

### CODE REVIEW

**Comment by deepak1556** [comment]
shit my git global config seems to be messed up, perks of using university server..

**Comment by jwerle** [comment]
@deepak1556 ha no worries. I was wondering who @navo was

**Comment by jwerle** [comment]
cc @stephenmathieson @larzconwell

**Comment by jwerle** [comment]
pretty big merge guys.. should we wait till libsphia is done? I'm envisioning us pretty much starting over with `sphia(1)` ...

thoughts ?

**Comment by deepak1556** [comment]
my thought was we will add changes to this branch as we update libsphia and finally merge this for v1.0 release when everything is in place.

**Comment by jwerle** [comment]
@deepak1556 I was thinking we need to restructure how we are compiling. I'd like to have separate binaries for the commands. See #62

**Comment by deepak1556** [comment]
that sounds much better, then a groud up refactoring would be good after libsphia is done.

**Comment by jwerle** [comment]
sweet ! :]

**Comment by stephenmathieson** [comment]
I'd like to restart too.  I figure we can start on #62 once libsphia is done.

**Comment by jwerle** [comment]
+1

**Comment by larzconwell** [comment]
+1 It'll be much better if we rewrite after libsphia.

**Pull request closed without merging**
